version: '2'
services:  
    nginx:
        build: nginx
        ports:
            - "443:443"  
        links:
            - varnish    
        #volumes:
        #    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        #    - ./nginx/app.conf:/etc/nginx/conf.d/app.conf      
        #restart: unless-stopped
    php:
        build: php7-fpm
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ${BASE_PROJECT_APP_PATH}:/var/www/base_project
            - ${SYMFONY_REALTIME_APP_PATH}:/var/www/symfony_realtime
            - ./logs/symfony:/var/www/symfony/app/logs
        links:            
            - db   
    nginx_webserver:
        build: nginx_webserver 
        ports:
            - "8081:80"
        volumes_from:
            - php            
        links:
            - php 
            - db
            - redis
        volumes:
            - ./logs/nginx/:/var/log/nginx    
        
    varnish:
        build: varnish
        #image: eeacms/varnish
        ports:
            - "80:81"
        depends_on:
            #- nginx_webserver
            - apache2
        links:
            #- nginx_webserver
            - apache2
        volumes:
            - ./varnish/:/var/www/varnish/config
        environment:
            #PORT_80_TCP_ADDR1: "nginx_webserver"
            PORT_80_TCP_ADDR2: "apache1"
            PORT_80_TCP_ADDR3: "apache2"
            PORT_80_TCP_ADDR4: "apache3"
            BACKENDS: "nginx_webserver"
            BACKENDS_PORT: "80"
            DNS_ENABLED: "true"
            BACKENDS_PROBE_INTERVAL: "3s"
            BACKENDS_PROBE_TIMEOUT: "1s"
            BACKENDS_PROBE_WINDOW: "2"
            BACKENDS_PROBE_THRESHOLD: "2"
            
    db:
        image: mysql
        ports:
            - 3307:3306        
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    redis:
        image: redis
        ports:
            - "6379" 
    apache1:
        build: apache2   
        volumes_from:
            - php       
        links:           
            - db
            - redis
        ports:
            - "8080:80"    
    apache2:
        build: apache2   
        volumes_from:
            - php       
        links:           
            - db
            - redis
    apache3:
        build: apache2   
        volumes_from:
            - php       
        links:           
            - db
            - redis        
            
        #ports:
        #    - "8080:80"    